tasks:
  - init: mvn package -Pproduction

    command: mvn
ports:
  - port: 8080
    onOpen: open-preview
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - runem.lit-plugin",
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
